application: megabusfinder
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/stylesheets
  static_dir: static/stylesheets
 

- url: /static/xml
  static_dir: static/xml
  #upload: static/xml

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
